export const chatCopy = {
  user: 'YOU',
  assistant: 'FORGE',
  network: 'The connection dropped. Please retry your message.',
  eyebrow: 'A4 / DESIGN STUDIO',
  title: 'Tell us what you see.',
  modifyTitle: 'Make room for your next idea.',
  subtitle: 'A name, a feeling, a community. Start anywhere. We will shape the details together.',
  summary: 'Your blueprint',
  summaryHint: 'Your answers become the specification for your launchpad.',
  fieldPending: 'Still to decide',
  message: 'Message',
  placeholder: 'Describe your launchpad…',
  modifyPlaceholder: 'What would you like to change?',
  send: 'Send message',
  typing: 'The builder is typing…',
  confirm: 'Confirm and go to payment',
  confirming: 'Confirming your blueprint…',
  edit: 'Ask for a change in the conversation before confirming.',
  ready: 'Your blueprint is ready',
  incomplete: 'A few details are still missing',
  limited: 'Slow down a bit. You have reached the message limit. Please try again shortly.',
  locked: 'On-chain settings are final. Trading fees, shares, and fee recipients cannot change.',
  included: 'Included changes left',
  request: 'Your change request',
  confirmChange: 'Confirm this change',
  labels: {
    name: 'Launchpad name',
    slug: 'Site address',
    tradingFeeBps: 'Trading fee',
    coinCreatorSharePct: 'Coin creators’ share',
    poolCreationFeeSol: 'Coin creation fee',
    antiSniper: 'Anti-sniper',
    'theme.primaryColor': 'Primary color',
    'theme.accentColor': 'Accent color',
    'theme.darkMode': 'Dark mode',
    'theme.tagline': 'Tagline',
    'theme.designNotes': 'Design notes',
    'launchpadCoin.name': 'Coin name',
    'launchpadCoin.symbol': 'Coin symbol',
    'launchpadCoin.imageUrl': 'Coin image',
    'launchpadCoin.description': 'Coin description',
    'launchpadCoin.firstBuySol': 'First buy',
    ownerWallet: 'Fee recipient',
  },
} as const;
