export const common = {
  brand: 'FORGE',
  workshop: 'THE WORKSHOP',
  footerBrand: 'FORGE / THE WORKSHOP',
  information: 'Information',
  navigation: 'Main navigation',
  faq: 'FAQ',
  terms: 'Terms',
  paused: 'Creation is paused, try again later.',
  creation: 'CREATION',
  modification: 'SITE CHANGE',
  address: 'address',
  countdown: (seconds: number) => `${seconds} seconds remaining`,
  home: 'Home',
  dashboard: 'My dashboard',
  create: 'Create a launchpad',
  connect: 'Connect wallet',
  disconnect: 'Disconnect',
  close: 'Close',
  retry: 'Try again',
  back: 'Back to dashboard',
  loading: 'Getting things ready',
  error: 'We could not load this view.',
  unavailable: 'The workshop is not connected yet.',
  unavailableBody:
    'Wallet connection and launchpad operations will be available when the service is connected. You can still explore the homepage.',
  demo: 'Design preview · simulated data. No wallet or funds are used.',
  preview: 'Preview',
  copied: 'Copied',
  copy: 'Copy',
  copyFailed: 'Copy unavailable. Select the full address below.',
  dark: 'Dark mode',
  light: 'Light mode',
  empty: 'Nothing here yet',
  missing: 'We could not find that launchpad or job.',
  support: 'Open help',
  sign: 'Sign in your wallet',
  sending: 'Sending…',
  confirmed: 'Confirmed',
  rejected: 'Signature declined. Nothing was sent.',
  txError: 'The transaction could not be completed. You can try again.',
  receipt: 'View confirmation',
  idle: 'Ready',
  claim: 'Claim my fees',
  noFees: 'Nothing to claim',
  claimExplanation:
    'Claim the available partner fees to your connected wallet. Your wallet will show the network fee before you sign.',
  rawUnits: 'raw token units',
  newTab: 'Open in a new tab',
  yes: 'Yes',
  no: 'No',
  pending: 'Not set yet',
  phases: ['Sign in your wallet', 'Sending…', 'Confirmed'],
} as const;
