export const dashboardCopy = {
  eyebrow: 'A8 / YOUR WORKSHOP',
  title: 'Worlds you are building.',
  subtitle: 'Manage your launchpads, collect your fees, and keep creating.',
  empty: 'Your first launchpad starts here.',
  emptyBody: 'Turn your idea into a place for your community.',
  coins: 'Coins launched',
  fees: 'Partner fees available',
  changes: 'Included changes left',
  view: 'View details',
  modify: 'Request a change',
  wake: 'Reactivate',
  waking: 'Reactivating…',
  job: 'Continue current job',
  status: { draft: 'Draft', live: 'Live', sleeping: 'Sleeping', disabled: 'Disabled' },
  sleep: 'This launchpad is sleeping. Reactivate it to welcome trading again.',
  disabled: 'This launchpad is disabled. Contact support for help.',
  claimSuccess: 'Fees claimed. Your balance has been refreshed.',
} as const;
