export const detailCopy = {
  eyebrow: 'A9 / LAUNCHPAD FILE',
  title: 'Every detail. All in one place.',
  settings: 'On-chain settings',
  final: 'On-chain settings are final.',
  versions: 'Version history',
  jobs: 'Job history',
  claimed: 'Claimed fees',
  noVersions: 'Your first version will appear after a preview is built.',
  noJobs: 'No jobs yet.',
  noClaimHistory: 'Claim history is not available from the service yet.',
  original: 'Initial creation',
  config: 'Launchpad config',
  coinConfig: 'Coin config',
  mint: 'Launchpad coin',
  pending: 'Available after on-chain setup',
  openJob: 'View job',
  preview: 'View preview',
  modify: 'Request a change',
} as const;
