export const galleryCopy = {
  eyebrow: 'A11 / COMPONENT LAB',
  title: 'Every state. One workshop.',
  body: 'Choose a screen and a scenario. These are the actual interface components with isolated mock data. Reset a scene to replay it.',
  reset: 'Reset scene',
  navigation: 'Screen states',
  missing: 'Scenario not found.',
  journey: 'Open the full journey',
  disabled: 'Enable the development mocks to open the state gallery.',
  command:
    'Start the web development server with NEXT_PUBLIC_USE_MOCKS=1. No environment file is required.',
  receipt: 'Simulated confirmation',
  receiptBody: 'This is a development receipt. No transaction was built, signed, or sent.',
  groups: [
    {
      id: 'global',
      title: 'Global states',
      states: [
        ['loading', 'Loading'],
        ['network-error', 'Network error and retry'],
        ['disconnected', 'Wallet not connected'],
        ['not-found', 'Missing record'],
      ],
    },
    {
      id: 'home',
      title: 'A1 · Homepage',
      states: [
        ['normal', 'Normal'],
        ['paused', 'Signups paused'],
      ],
    },
    {
      id: 'session',
      title: 'A2 · Wallet connection',
      states: [
        ['choice', 'Wallet choice'],
        ['signing', 'Waiting for signature'],
        ['rejected', 'Signature rejected'],
        ['error', 'Connection error'],
        ['connected', 'Connected'],
      ],
    },
    {
      id: 'gating',
      title: 'A3 · Access check',
      states: [
        ['checking', 'Checking'],
        ['ok', 'Sufficient balance'],
        ['insufficient', 'Insufficient balance'],
        ['disabled', 'Check disabled before launch'],
      ],
    },
    {
      id: 'chat',
      title: 'A4 · Design chat',
      states: [
        ['welcome', 'Welcome'],
        ['conversation', 'Conversation'],
        ['streaming', 'Streaming response'],
        ['incomplete', 'Invalid specification'],
        ['ready', 'Ready to confirm'],
        ['confirming', 'Confirming'],
        ['error', 'Message error'],
        ['rate-limited', 'Message limit'],
        ['modification', 'Change request'],
      ],
    },
    {
      id: 'payment',
      title: 'A5 · Payment',
      states: [
        ['loading', 'Quote loading'],
        ['ready', 'Quote ready'],
        ['expires-soon', 'Expires after 10 seconds'],
        ['signing', 'Signing'],
        ['sending', 'On-chain confirmation'],
        ['confirmed', 'Paid'],
        ['expired', 'Expired quote'],
        ['check-failed', 'Payment check rejected'],
        ['rejected', 'Signature declined'],
        ['included', 'Included change'],
      ],
    },
    {
      id: 'job',
      title: 'A6 · Job tracking',
      states: [
        ['spec_ready', 'Awaiting payment'],
        ['paid', 'Paid'],
        ['building', 'Building'],
        ['preview_ready', 'Preview ready'],
        ['approved', 'Approved'],
        ['onchain_setup', 'Connecting to Meteora'],
        ['awaiting_owner_signature', 'Your turn to sign'],
        ['owner_signed', 'Launch signed'],
        ['deploying', 'Going live'],
        ['live', 'Live'],
        ['retry', 'Fails once, then succeeds'],
        ['build-exhausted', 'Waiting for refund'],
        ['failed-onchain', 'On-chain failure'],
        ['deploy-failed', 'Deployment failure'],
        ['refunded', 'Refunded'],
        ['building-modification', 'Change tracker'],
      ],
    },
    { id: 'journey', title: 'Automatic journey', states: [['auto', 'One step every 3 seconds']] },
    {
      id: 'launch',
      title: 'A7 · Coin launch',
      states: [
        ['preparing', 'Preparing'],
        ['ready', 'Ready'],
        ['signing', 'Signing'],
        ['sending', 'Sending'],
        ['confirmed', 'Confirmed'],
        ['send-error', 'Send failure'],
        ['wrong-wallet', 'Wrong wallet'],
      ],
    },
    {
      id: 'dashboard',
      title: 'A8 · Dashboard',
      states: [
        ['loading', 'Loading'],
        ['empty', 'No launchpads'],
        ['one', 'One launchpad'],
        ['three', 'Live, sleeping, disabled'],
        ['draft', 'Draft launchpad'],
        ['active-job', 'Current job'],
        ['claim-signing', 'Claim signature'],
        ['claim-sending', 'Claim sending'],
        ['claim-confirmed', 'Claim successful'],
        ['claim-rejected', 'Claim rejected'],
        ['no-fees', 'Nothing to claim'],
      ],
    },
    {
      id: 'detail',
      title: 'A9 · Launchpad detail',
      states: [
        ['loading', 'Loading'],
        ['ready', 'Settings and history'],
      ],
    },
    {
      id: 'information',
      title: 'A10 · Information',
      states: [
        ['faq', 'FAQ'],
        ['terms', 'Provisional terms'],
      ],
    },
  ],
} as const;
export const galleryScenarios = galleryCopy.groups.flatMap((group) =>
  group.states.map(([state, label]) => ({
    id: `${group.id}:${state}`,
    group: group.id,
    state,
    label,
  })),
);
