export const jobCopy = {
  progress: 'Build progress',
  eyebrow: 'A6 / IN THE MAKING',
  title: 'From blueprint to live.',
  log: 'Workshop activity',
  noEvents: 'Waiting for the first update…',
  steps: [
    'Paid',
    'Building',
    'Preview ready',
    'Approved',
    'Connecting to Meteora',
    'Signing the launch',
    'Going live',
    'Live',
  ],
  preview: 'Meet your launchpad.',
  previewBody: 'Explore the preview, then approve it when it feels right.',
  approve: 'Approve the preview',
  approving: 'Approving…',
  change: 'Request a change',
  changeNote: 'A new request counts as a site change.',
  payment: 'Continue to payment',
  sign: 'Review and sign the launch',
  retrying: 'Retrying automatically',
  attempt: 'Build attempt',
  team: 'Something went wrong. Our team has been notified and is on it.',
  refundPending: 'Both build attempts failed. Waiting for the refund confirmation.',
  refunded: 'Your payment was refunded.',
  live: 'You are live.',
  liveBody: 'Your launchpad is ready for its first community.',
  site: 'Visit launchpad',
  dashboard: 'Open dashboard',
  share: 'Copy site link',
  unavailable: 'The site link is not available yet.',
  setup: 'Connecting your launchpad to Meteora…',
  deploying: 'Taking your launchpad live…',
  building: 'Your launchpad is taking shape.',
  waiting: 'Your next step is ready.',
  frame: 'Launchpad preview',
} as const;
