import { z } from 'zod';
import { Slug, SolanaAddress } from './spec.js';

export const SolanaCluster = z.enum(['devnet', 'mainnet-beta']);
export type SolanaCluster = z.infer<typeof SolanaCluster>;

/** `live`, `sleeping` (dormant) or `disabled` (cut by FORGE). Written by the builder only. */
export const SiteMode = z.enum(['live', 'sleeping', 'disabled']);
export type SiteMode = z.infer<typeof SiteMode>;

const HexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/);

/**
 * `forge.config.json`, generated by the builder in each client repo and read by the client site
 * (docs/INTERFACES.md §3). The builder agent may change `theme` and `content`, never `onchain`
 * nor `mode`. FORGE addresses (multisig, referrals, platform fee wallet) are NOT in this file.
 */
export const ForgeSiteConfig = z.object({
  version: z.literal(1),
  name: z.string().min(2).max(32),
  slug: Slug,
  mode: SiteMode,
  /** Absent until the on-chain setup is done. */
  onchain: z
    .object({
      cluster: SolanaCluster,
      launchpadConfig: SolanaAddress,
      launchpadCoinConfig: SolanaAddress,
      launchpadCoinMint: SolanaAddress,
      ownerWallet: SolanaAddress,
    })
    .optional(),
  theme: z.object({
    primaryColor: HexColor,
    accentColor: HexColor,
    darkMode: z.boolean(),
  }),
  content: z.object({
    tagline: z.string().max(120),
    about: z.string(),
  }),
});
export type ForgeSiteConfig = z.infer<typeof ForgeSiteConfig>;

/** Read-only view of forge.config.json exposed to the template UI (docs/frontend/CONTRACT.md). */
export interface SiteConfig {
  name: string;
  slug: string;
  theme: { primaryColor: string; accentColor: string; darkMode: boolean };
  content: { tagline: string; about: string };
  mode: SiteMode;
}

/** Pure projection of a parsed forge.config.json to the UI-facing SiteConfig. */
export function toSiteConfig(config: ForgeSiteConfig): SiteConfig {
  return {
    name: config.name,
    slug: config.slug,
    theme: { ...config.theme },
    content: { ...config.content },
    mode: config.mode,
  };
}
